# Generated by Django 2.2.24 on 2022-06-07 14:53

from django.db import migrations


def set_construction_year(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    flats.objects.filter(construction_year__lt=2015).update(new_building=False)
    flats.objects.filter(construction_year__gte=2015).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_construction_year),
    ]
