# Generated by Django 2.2.24 on 2022-06-08 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20220607_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliant_text', models.TextField(verbose_name='Текст жалобы')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flat_compliants', to='property.Flat', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_compliants', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
