# Generated by Django 2.2.24 on 2022-06-15 11:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220615_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон владельца'),
        ),
        migrations.AddField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный телефон владельца'),
        ),
    ]
