# Generated by Django 2.2.24 on 2022-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220615_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.CharField(max_length=200, verbose_name='ФИО владельца'),
        ),
    ]
