# Generated by Django 2.2.24 on 2022-06-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220618_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(db_index=True, related_name='owner_flats', to='property.Flat', verbose_name='Квартира'),
        ),
    ]
