# Generated by Django 2.2.24 on 2022-06-18 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def f_pass(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0018_auto_20220618_1823'),
    ]

    operations = [
        migrations.RunPython(f_pass)
    ]
