# Generated by Django 2.2.24 on 2022-06-19 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0020_auto_20220618_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliant',
            name='owner',
        ),
        migrations.AddField(
            model_name='compliant',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_compliants', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался'),
            preserve_default=False,
        ),
    ]
