# Generated by Django 2.2.24 on 2022-06-22 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20220619_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliant',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compliants', to='property.Flat', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='compliant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='compliants', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался'),
        ),
    ]
