# Generated by Django 2.2.24 on 2022-06-25 10:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20220622_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliant',
            old_name='compliant_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Телефон владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region=None, verbose_name='Нормализованный телефон владельца'),
        ),
    ]
