# Generated by Django 2.2.24 on 2022-06-25 11:16

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0025_auto_20220622_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compliant',
            old_name='compliant_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='like',
            new_name='likes'
        ),

        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats'
        ),
    ]
